---
title: "Invasive_wrack_manuscript_code"
author: "Ric DeSantiago"
date: "12/15/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---
#libraries
```{r libraries}
library(knitr)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(ggfortify)
library(lme4)
library(car)
library(nlme)
library(ggpubr)
library(multcompView)
library(boot)
library(Hotelling)
library(mvnTest)
library(vegan)
library(factoextra)
library(FactoMineR)
library(agricolae)
library(glmm)
library(HH)
library(ggpubr)
library(rstatix)

#hi
```


#Load Field Surveys
```{r}

wrack<-read.csv("InvasiveWrackSurveySNIJan2020.csv", header = TRUE)
view(wrack)
Grazer_Survey_Data <- read.csv("GrzrOnOffSurveySNIJan2020.csv") 
view(Grazer_Survey_Data)

```

##Wrack surveys
```{r}
#make a new column in datasheet for the proportion of total wrack patty area made up of sargassum
wrack$propsarg <- wrack$sarg_total / wrack$ellipse_A_m2

#make new column to show proportion of total made up of macrocystis (1-sargassum)
wrack$propmac<- 1 - wrack$propsarg

#make graph to show these proportions
ggplot(data=wrack, aes(x=site, y=propmac, fill=propsarg)) +
  geom_bar(stat="identity")

```

##Invasive Wrack usage survey
```{r}
Grazer_Survey_Data <- read.csv("GrzrOnOffSurveySNIJan2020.csv") 

#we want to remove any row that has double 0's, so a 0 for on and a 0 for off, this is because not every recorder recorded 0's when animals weren't seen. Therefore, by keeping double 0's in, we're inflating the likelihood of not finding an animal

Grazer_Survey_Data_edited <- Grazer_Survey_Data 
Grazer_Survey_Data_edited<- mutate(Grazer_Survey_Data_edited, Grazer_sum = on_wrack + off_wrack) 
filter(Grazer_Survey_Data_edited, Grazer_sum != 0)
#this removed 13 observations

#create a dataframe with just important columns
Grazer_Survey_Data_reduced <- na.omit(Grazer_Survey_Data_edited[, -c(1:3, 5, 7)])

#Change to long format
Grazer_Survey_Data_long <- gather(data = Grazer_Survey_Data_reduced, 
                                 key = "Wrack.Use", value = "Grazer_sum", c(on_wrack, off_wrack), factor_key = TRUE)

#Barplot
barplot<- ggplot(Grazer_Survey_Data_long, aes(fill=Wrack.Use, y=Grazer_sum, x=grzr_sp)) + 
    geom_bar(position="dodge", stat="identity")

barplot


pdf(file = "On.off_grazersurvey_Jan2020SanNic.pdf", width = 6, height = 4, useDingbats=F)

Plot_Bar_g <- ggplot(data=meanAbundance_grazer,
                      aes(y=mean_Abundance, 
                          x=grzr_sp, 
                          fill = Wrack.Use)) +
  geom_bar(stat = "identity", colour = "black", 
           position = position_dodge(width = 0.9))

Plot_Bar_g + theme(axis.title.x = element_text(face="bold",
                                                 size=22),
                           axis.text.x  = element_text(size=20)) + 
  xlab("Grazer") +
  theme(axis.title.y = element_blank()) + 
  ylab("Count (max 20)") +
  theme(axis.title.y = element_text(angle=90, 
                                    face="bold", 
                                    size=22, 
                                    vjust=1.5),
        axis.text.y  = element_text(size=20)) +
  geom_errorbar(aes(ymin=mean_Abundance - SE, 
                    ymax=mean_Abundance + SE), width = 0.05,
                position=position_dodge(width = 0.9)) +
  scale_fill_manual(name = "Wrack usage",
                    values = c("#999999", "#009E73")) +
  theme(legend.justification=c(.5,.5), legend.position=c(.18,.88)) +
  scale_y_continuous(expand = expand_scale(mult = c(0, 0)),
                     breaks = pretty(c(0,20), n = 5), 
                     limits = c(0,20))

dev.off()

#let's extract the sample sizes for each of the grazers bc we didn't see grazers everytime

Grazer_Survey_Data_reduced %>% 
  count(grzr_sp)

```


#Choice Assays
```{r}
#import and name data
LabAssayWholeTissue <-read.csv("LabAssaysWholeTissue.csv",header=T)
View(LabAssayWholeTissue)

#ensure factors are correctly read
is.numeric(LabAssayWholeTissue$algae_Wd)
is.factor(LabAssayWholeTissue$algae_spp.)


AllSpeciesWholeTissue<-ggplot(LabAssayWholeTissue, aes(x=grazer_spp., y=algae_Wd, fill= algae_spp.)) + geom_boxplot() + theme_bw()   + xlab("Algae Species") + ylab("Total Consumed (g)") + ggtitle("Live algae choice assay") + theme(plot.title =element_text(hjust = 0.5))
AllSpeciesWholeTissue
```

##Tegula

```{r}
#read and rename file
WholeTissueAssay <- read.csv("LabAssaysWholeTissue.csv",header=T)
View(WholeTissueAssay)

#subset the tegula rows
tegula<-subset(LabAssayWholeTissue, grazer_spp.== "Tegula")
view(tegula)

#since controls were solely used for correction of autogenic growth, we can further subset to only look at the experimental treatments
tegulachoice <- subset(tegula, trt == "exp")
view(tegulachoice)

#visualize data

#look at the data in boxplots to visualize the spread around the median
ggplot(tegulachoice, aes(x=algae_spp., y=algae_Wd)) + geom_boxplot()
#there seems to be an outlier in each treatment that may be pulling distributions, however, we are leaving outliers in as they are biological real, some animals may simply eat more than others.

#separate the histogram by species of algae to visually determine if the distributions of differences (f-i, adjusted for autogenic growth) look normal
#sargassum
tegulachoicesarg<-subset(tegulachoice, algae_spp. == "sargassum")
ggplot(tegulachoicesarg, aes(x=algae_Wd)) + geom_histogram(binwidth=0.1)
mean(tegula$algae_Wd[tegula$algae_spp.== 'sargassum'],na.rm = T)
sd(tegula$algae_Wd[tegula$algae_spp.== 'sargassum'],na.rm = T)
#macrocystis
tegulachoicemacro<-subset(tegulachoice, algae_spp. == "macro")
ggplot(tegulachoicemacro, aes(x=algae_Wd)) + geom_histogram(binwidth=0.1)
mean(tegula$algae_Wd[tegula$algae_spp.== 'macro'],na.rm = T)
sd(tegula$algae_Wd[tegula$algae_spp.== 'macro'],na.rm = T)

#the data do not look normal for the samples, Ds of weight in sargassum tend to be right leaning while macro samples tend to be left learning
#test for normality
par(mfrow=c(2,2))
qqnorm(tegulachoicemacro$algae_Wd)
qqline(tegulachoicemacro$algae_Wd)
qqnorm(tegulachoicesarg$algae_Wd)
qqline(tegulachoicesarg$algae_Wd)

#our data fail the normality assumption for a T-test
##our data are not independent since they are a choice between two options of algae
### To address the question "Do grazers show a preference between S. horneri or M. pyrifera?" we will use consuption as a proxy for choice. Thus, we can use a paired T test to see if there is a difference in "t"otal consumed" between S. horneri and M. pyrifera.
####Paired t-tests are essentially one-sample t-tests, but you are comparing a distribution of DIFFERENCES to a theoretical one rather than a distribution of sample statistics. Thus, the original data are not used, rather the mean, variance, and standard ddviation are baed on the DIFFERENCES. Thus, we don't need equal variances, only normal distribution of means and equal sample size. 

#check for normality
ggplot(tegulachoice, aes(x=algae_Wd)) + geom_histogram(binwidth=0.1)
qqnorm(tegulachoice$algae_Wd)
qqline(tegulachoice$algae_Wd)
#there seems to be an outlier, however, the data look normally distributed around the theoretical line

#we will conduct a paired-T test.
## H0: There is no difference in total consumed between S. horneri and M. pyrifera  (i.e. there is no choice between algae).
## HA: There is a difference in total consumed between S. horneri and M. pyrifera  (i.e. there is a choice between algae).

#T test
t.test(tegulachoice$algae_Wd~tegulachoice$algae_spp., paired= TRUE)
## we reject the null hypothesis (t = 5.7152, df = 13, p-value = 7.111e-05), there was a choice made between algae


#make boxplot 
ggplot(tegula, aes(x=algae_spp., y=algae_Wd, fill= algae_spp.))+ geom_boxplot() + theme_bw()  + guides() + xlab("Algae Species") + ylab(" Consumtion (g)") + ggtitle("M. pyrifera vs. S. horneri whole tissue consumption by T. funebralis") + theme(plot.title =element_text(hjust = 0.5)) 

#When given a choice between S. horneri and M. pyrifera, Tegula preferred M. pyrifera.

##this will be repeated for all other grazers.

```


##Pachy
```{r}
#subset the P. crassipes rows
pachy<-subset(LabAssayWholeTissue, grazer_spp.== "Pachy")
view(pachy)

#since controls were solely used for correction of autogenic growth, we can further subset to only look at the experimental treatments
pachychoice <- subset(pachy, trt == "exp")
view(pachychoice)

#visualize data

#look at the data in boxplots to visualize the spread around the median
ggplot(pachychoice, aes(x=algae_spp., y=algae_Wd)) + geom_boxplot()
#there seems to be an outlier in the S. horneri treatment that may be pulling the distribution

##due to failed assumptions for T-sample t test (See lines 180+), we will test the nomrality by looking at the distribution of the differences and conduct a Paired T test

#check for normality
ggplot(pachychoice, aes(x=algae_Wd)) + geom_histogram(binwidth=0.1)
qqnorm(pachychoice$algae_Wd)
qqline(pachychoice$algae_Wd)
#there seems to be an outlier, however, the data look normally distributed around the theoretical line

#we will conduct a paired-T test.
## H0: There is no difference in total consumed between S. horneri and M. pyrifera  (i.e. there is no choice between algae).
## HA: There is a difference in total consumed between S. horneri and M. pyrifera  (i.e. there is a choice between algae).

#T test
t.test(pachychoice$algae_Wd~pachychoice$algae_spp., paired= TRUE)
## we fail reject the null hypothesis (t = 0.073928, df = 13, p-value = 0.9422), there was no choice made between algae


#make boxplot 
ggplot(pachy, aes(x=algae_spp., y=algae_Wd, fill= algae_spp.))+ geom_boxplot() + theme_bw()  + guides() + xlab("Algae Species") + ylab(" Consumtion (g)") + ggtitle("M. pyrifera vs. S. horneri whole tissue consumption by P. crassipes ") + theme(plot.title =element_text(hjust = 0.5)) 

#When given a choice between S. horneri and M. pyrifera, P. Crassipes showed no preference.
```

##Pagurus
```{r}

#subset the P. samuelis rows
pagurus<-subset(LabAssayWholeTissue, grazer_spp.== "Pagurus")
view(pagurus)

#since controls were solely used for correction of autogenic growth, we can further subset to only look at the experimental treatments
paguruschoice <- subset(pagurus, trt == "exp")
view(paguruschoice)

#visualize data

#look at the data in boxplots to visualize the spread around the median
ggplot(paguruschoice, aes(x=algae_spp., y=algae_Wd)) + geom_boxplot()

##due to failed assumptions for T-sample t test (See lines 180+), we will test the nomrality by looking at the distribution of the differences and conduct a Paired T test

#check for normality
ggplot(paguruschoice, aes(x=algae_Wd)) + geom_histogram(binwidth=0.1)
qqnorm(paguruschoice$algae_Wd)
qqline(paguruschoice$algae_Wd)
#there seems to be an outlier on both ends, however, the data look normally distributed around the theoretical line

#we will conduct a paired-T test.
## H0: There is no difference in total consumed between S. horneri and M. pyrifera  (i.e. there is no choice between algae).
## HA: There is a difference in total consumed between S. horneri and M. pyrifera  (i.e. there is a choice between algae).

#T test
t.test(paguruschoice$algae_Wd~paguruschoice$algae_spp., paired= TRUE)
## we reject the null hypothesis (t = -3.7593, df = 13, p-value = 0.002385), there was a choice made between algae


#make boxplot 
ggplot(pagurus, aes(x=algae_spp., y=algae_Wd, fill= algae_spp.))+ geom_boxplot() + theme_bw()  + guides() + xlab("Algae Species") + ylab(" Consumtion (g)") + ggtitle("M. pyrifera vs. S. horneri whole tissue consumption by P. samuelis ") + theme(plot.title =element_text(hjust = 0.5)) 

#When given a choice between S. horneri and M. pyrifera, P. samuelis showed a preference for sargassum .
```

##Abalone September 2019
```{r}

#subset the A. cracherodii rows
abalone<-subset(LabAssayWholeTissue, grazer_spp.== "Haliotis cracherodii")
view(abalone)

#since controls were solely used for correction of autogenic growth, we can further subset to only look at the experimental treatments
abalonechoice <- subset(abalone, trt == "Experimental")
view(abalonechoice)

#visualize data

#look at the data in boxplots to visualize the spread around the median
ggplot(abalonechoice, aes(x=algae_spp., y=algae_Wd)) + geom_boxplot()

##due to failed assumptions for T-sample t test (See lines 180+), we will test the nomrality by looking at the distribution of the differences and conduct a Paired T test

#check for normality
ggplot(abalonechoice, aes(x=algae_Wd)) + geom_histogram(binwidth=0.5)
qqnorm(abalonechoice$algae_Wd)
qqline(abalonechoice$algae_Wd)
#the data seem pretty normal

#we will conduct a paired-T test.
## H0: There is no difference in total consumed between S. horneri and M. pyrifera  (i.e. there is no choice between algae).
## HA: There is a difference in total consumed between S. horneri and M. pyrifera  (i.e. there is a choice between algae).

#T test
t.test(abalonechoice$algae_Wd~abalonechoice$algae_spp., paired= TRUE)
## we reject the null hypothesis (4.5053, df = 15, p-value = 0.0004189), there was a choice made between algae


#make boxplot 
ggplot(abalonechoice, aes(x=algae_spp., y=algae_Wd, fill= algae_spp.))+ geom_boxplot() + theme_bw()  + guides() + xlab("Algae Species") + ylab(" Consumtion (g)") + ggtitle("M. pyrifera vs. S. horneri whole tissue consumption by H. cracherodii ") + theme(plot.title =element_text(hjust = 0.5)) 

#When given a choice between S. horneri and M. pyrifera, H. cracherodii showed a preference for M. pyriferae.

```



#Performance Assays March-April 2020
```{r}
#load data
performance<-read.csv("PerformanceAssays2020.csv", header=TRUE)
view(performance)
na.omit(performance)

is.numeric(performance$wetmass_total_Wd)
performance$wetmass_total_Wd<-as.numeric(performance$wetmass_total_Wd)
is.factor(performance$treatment)
performance$treatment<-as.factor(performance$treatment)


#create new column to look at weight difference (Wf-Wi) as a percent of initial weight (Wd/Wi *100) to visualize rough weight differences
performance<-mutate(performance, percent_change = performance$wetmass_total_Wd / performance$wetmass_i* 100)
view(performance)

```


##Red Abalone
```{r}

#subset data for abalone
redabaloneperformance<-subset(performance, grazer_spp.== "red abalone")
view(redabaloneperformance)

#visualize data
ggplot(redabaloneperformance, aes(y=redabaloneperformance$percent_change, x=diet)) + geom_boxplot()
#histogram
ggplot(redabaloneperformance, aes(x=redabaloneperformance$percent_change)) + geom_histogram(binwidth=1)
#the data look fairly normal when combined, the histogram shows the distribution tailes to the left having some numbers in the negative, this is likely due to the starved treatment.
## Starved treatment is used as a control and to detect if any food treatment is worse than starvation (e.g., toxic and harmful algae)

#From here forward, we will compare data without the starved treatment

#view the data. We will be analyzing using either a GLM or ANOVA but we must look at the data to determine what is the best analysis. 

#make boxplot for initial wet mass
ggplot(redabaloneperformance, aes(x=diet, y=wetmass_i , fill= diet)) + geom_boxplot() + theme_bw()   + xlab("Diet") + ylab(" wet mass") + ggtitle("H. rufescens initial wet mass") + theme(plot.title =element_text(hjust = 0.5))
#there seems to be a difference in means of starting weights of animals in each treatment, we can account for these different starting weights using initial weight as a covariate or a random factor

#make boxplot of final wet weight
ggplot(redabaloneperformance, aes(x=diet, y=wetmass_f , fill= diet)) + geom_boxplot() + theme_bw()   + xlab("Diet") + ylab(" wet mass") + ggtitle("H. rufescens final wet mass") + theme(plot.title =element_text(hjust = 0.5))
# the pattern we see here seems to be consistent with initial weight with the expected weight decrease in the starved treatment

#make boxplot of percent change in wetmass by diet
ggplot(redabaloneperformance, aes(x= diet , y= percent_change, fill = diet )) + theme_bw() + geom_boxplot() + ggtitle("H. rufescens percent change in total mass") + ylab("Total mass change (%)") + xlab("Diet Treatment") + guides(fill= F) + theme(plot.title =element_text(hjust = 0.5))

#make boxplot of final tissue dry mass by diet
ggplot(redabaloneperformance, aes(x=diet, y=terminal_dry_mass, fill= diet)) + geom_boxplot() + theme_bw()   + xlab("Diet") + ylab("Tissue Dry Mass (g)") + ggtitle("H. rufescens final dry mass by diet") + theme(plot.title =element_text(hjust = 0.5))
#means of mass change are positive for the three food diets and negative for the starved treatment

#look at mass based on tissue type
#make boxplot of final gonad/gill/digestive dry mass by diet
ggplot(redabaloneperformance, aes(x=diet, y=gonad_dry_mass, fill= diet)) + geom_boxplot() + theme_bw()   + xlab("Diet") + ylab("Gonad Dry Mass (g)") + ggtitle("H. rufescens final gonad/gill/GI mass by diet") + theme(plot.title =element_text(hjust = 0.5))

#make boxplot of final foot dry mass by diet
ggplot(redabaloneperformance, aes(x=diet, y=nongonad_dry_mass, fill= diet)) + geom_boxplot() + theme_bw()   + xlab("Diet") + ylab("Tissue Dry Mass (g)") + ggtitle("H. rufescens final non-gonad dry mass by diet") + theme(plot.title =element_text(hjust = 0.5))

#make boxplot of final shell dry mass by diet
ggplot(redabaloneperformance, aes(x=diet, y=terminal_shell_dry_mass , fill= diet)) + geom_boxplot() + theme_bw()   + xlab("Diet") + ylab("Shell Dry Mass (g)") + ggtitle("H. rufescens final shell dry mass by diet") + theme(plot.title =element_text(hjust = 0.5))


#test if there is a significant difference in initial wet masses using a simple anova
initialmassabs<-aov(redabaloneperformance$wetmass_i ~ redabaloneperformance$diet)
summary(initialmassabs)
#we fail to reject the null hypothesis (p = 0.24), the means are not different. 

#we can proceed to the analysis without using initial wet mass as a covariate. However, we can account for different starting points (intercepts) by using initial mass as a random factor.


# Build the linear model to test normality
model  <- lm(terminal_dry_mass ~ diet, data = redabaloneperformance)
# Create a QQ plot of residuals
ggqqplot(residuals(model))
#there is a slight U shaped pattern in the data where the distribution deviates from the expected line in the upward direction on both ends and droops in the middle

#testing normality with a Shapiro-Wilk test
shapiro_test(residuals(model))
#SW test rejects the Ho(p=0.01308574), thus we accept the alternative H that the data are not normally distributed.

#Since the data are not normal, we can't use a Barlette test for equal variance, instead we will use a Levene Test
leveneTest(terminal_dry_mass~diet, data=redabaloneperformance)
#Levene test fails to reject the null Ho (p-value = 0.07774), thus we accept the hypothesis that our variances are equal

#general linear model will not work for our data if we were just looking at the impact of diet on abalone mass, however, we want to account for starting differences in weight.
##because our initial weights were in wet mass, they will be higher in total value and introduce more variablity due to water weight, thus, we cannot use those values
###We will account for initial weights of animals by estimating initial dry mass using shell length to predict dry mass as calculated using our intial sample's above in "initial weight estimates"
####We calculated these numbers using a linear regression and then input the estimated initial values into the original datasheet "PerformanceAssay2020.csv"

#To remind us of the question we want to ask "does diet impact abalone weight?"
##We think that diet will cause differences in weight, however, we know that initial weight matters and individual growth rates matter.
###But, we are not interested in how individual abalone grow relative to each other, regardless, we need to account for the variation introduced by this.
####We also know that starting weight matters, as many animals grow more rapidly when young and asymptote as they grow, etc.
######Thus we can account for this variation with a generalized linear model

testing <- glmm(terminal_dry_mass ~ diet + (1|est_total_dry_mass_i),
                family=gaussian (link = "identity"), data=redabaloneperformance)
summary(testing)

mixed.model<-lmer(terminal_dry_mass ~ diet + (1|est_total_dry_mass_i), data = redabaloneperformance)
summary(mixed.model, corr=F)

dotchart(sort(xtabs(~ est_total_dry_mass_i), cex=0.7))











ancova_model <- aov(terminal_dry_mass ~ diet*est_total_dry_mass_i, data = redabaloneperformance)
Anova(ancova_model, type="III")

redab.aov.HSD1 <- HSD.test(ancova_model, trt = 'diet') 
print(redab.aov.HSD1)
plot(redab.aov.HSD1)




```


## Tegula
```{r}
#subset data for tegula
tegulaperformance<-subset(performance, grazer_spp.== "tegula")

#histogram
ggplot(tegulaperformance, aes(x=terminal_dry_mass)) + geom_histogram()

#make boxplot of percent change by diet
ggplot(tegulaperformance, aes(x= diet , y= percent_change, fill = diet )) + theme_bw() + geom_boxplot() + ggtitle("T. funebralis percent change in total mass") + ylab("Total mass change (%)") + xlab("Diet Treatment") + guides(fill= F) + theme(plot.title =element_text(hjust = 0.5))


#make boxplot of final tissue dry mass by diet
ggplot(tegulaperformance, aes(x=diet, y=terminal_dry_mass, fill= treatment)) + geom_boxplot() + theme_bw()   + xlab("Diet") + ylab("Tissue Dry Mass (g)") + ggtitle("Tegula final dry mass by diet") + theme(plot.title =element_text(hjust = 0.5))


#make boxplot of final shell dry mass by diet
ggplot(tegulaperformance, aes(x=diet, y=terminal_shell_dry_mass , fill= treatment)) + geom_boxplot() + theme_bw()   + xlab("Diet") + ylab("Shell Dry Mass (g)") + ggtitle("Tegula final shell dry mass by diet") + theme(plot.title =element_text(hjust = 0.5))


#run analysis of variance using aov function
tegaov<- aov(tegulaperformance$percent_change ~ tegulaperformance$diet)
#view aov stats
summary(tegaov)

#check assumptions of ANOVA
# check Levene's test for constant variance
leveneTest(tegaov)
## null hypothesis is that we have constant variance
### P=0.55, do not reject the hypothesis

#check the normality of the residuals
qqnorm(tegaov$residuals)
shapiro.test(tegaov$residuals)
##resuduals are normally distributed

#Tukeys post hoc test
teg.aov.HSD <- HSD.test(tegaov, trt = 'tegulaperformance$diet') 
print(teg.aov.HSD)
plot(teg.aov.HSD)



```



##Righting times
```{r}
performance<-read.csv("PerformanceAssays2020.csv", header=TRUE)
view(performance)
na.omit(performance)

#subset the abalone 
abperf<-subset(performance, grazer_spp.== "red abalone")

#wrangle data to show attempt 1 and attempt 2 side by side for each treatment
gathered_obs<-gather(abperf, key="righting", value="time", 24:25)
view(gathered_obs)
na.omit(gathered_obs)
is.factor(gathered_obs$righting)
as.factor(gathered_obs$righting)

#make boxplot
ggplot(gathered_obs, aes(x= diet , y= time, fill = righting )) + theme_bw() + geom_boxplot()


ggplot(gathered_obs, aes(x=diet, y=time, fill= righting)) +
  geom_bar(stat="identity",position=position_dodge())+theme_minimal()

```
#Initial weight estimates
```{r }
#read and rename file
regressions <- read.csv("regressiondata.csv",header=T)
View(regressions)

#subset abalone
regressionsub<-subset(regressions, Species == "Ab")

#subset tegula
regressiontegsub<-subset(regressions, Species == "Teg")
view(regressiontegsub)

```

## Abalone Models
```{r }

#explore data
mean(regressionsub$Dissected_sum_drytissue)
sd(regressionsub$Dissected_sum_drytissue)
hist(regressionsub$Dissected_sum_drytissue)
mean(regressionsub$Shell_L)
sd(regressionsub$Shell_L)
hist(regressionsub$Shell_L)

#simple scatterplot and pearson correlation
plot(regressionsub$Dissected_sum_drytissue, regressionsub$Shell_L, data = regressionsub, main = "scatterplot")
cor(regressionsub$Dissected_sum_drytissue, regressionsub$Shell_L)


#Abalone models 
#model 1
#regression to predict dry tissue
mod<-lm(Dissected_sum_drytissue ~ Shell_L, data = regressionsub)
summary(mod)
attributes(mod)

#add the line
abregplot<- plot(regressionsub$Shell_L, regressionsub$Dissected_ab_gonad_dry_weight, main = "regression",
     xlab = "Shell Length", ylab = "Total Dry Tissue",
     pch = 19, frame = FALSE) +
abline(lm(regressionsub$Dissected_ab_gonad_dry_weight ~ regressionsub$Shell_L)) 


#model 2

#regression to predict body dry tissue
mod2<-lm(Dissected_ab_nongonad_dry_weight ~ Shell_L, data = regressionsub)
summary(mod2)
attributes(mod2)

#add the line
abregplot2<- plot(regressionsub$Shell_L, regressionsub$Dissected_ab_nongonad_dry_weight, main = "regression",
     xlab = "Shell Length", ylab = "Foot Dry Tissue",
     pch = 19, frame = FALSE) +
abline(lm(regressionsub$Dissected_ab_nongonad_dry_weight ~ regressionsub$Shell_L)) 


#Model3

#regression to predict gill/gut/gonad tissue
mod3<-lm(Dissected_ab_gonad_dry_weight ~ Shell_L, data = regressionsub)
summary(mod3)
attributes(mod3)

#add the line
abregplot3<- plot(regressionsub$Shell_L, regressionsub$Dissected_ab_gonad_dry_weight, main = "regression",
     xlab = "Shell Length", ylab = "Gill/gut/gonad complex Dry Tissue",
     pch = 19, frame = FALSE) +
abline(lm(regressionsub$Dissected_ab_gonad_dry_weight ~ regressionsub$Shell_L)) 

```


## Tegula Models
```{r }
#Tegula Model

#explore data
mean(regressiontegsub$Dissected_sum_drytissue)
sd(regressiontegsub$Dissected_sum_drytissue)
hist(regressiontegsub$Dissected_sum_drytissue)

#model4 dry tegula tissue
mod4<-lm(Dissected_sum_drytissue ~ Real_L, data = regressiontegsub)
summary(mod4)
attributes(mod4)

#add the line
abregplot4<- plot(regressiontegsub$Real_L, regressiontegsub$Dissected_sum_drytissue, main = "regression",
     xlab = "Shell Length", ylab = "Tegula Whole Tissue",
     pch = 19, frame = FALSE) +
abline(lm(regressiontegsub$Dissected_sum_drytissue ~ regressiontegsub$Real_L)) 

 
```

#Figures for Manuscript
```{r}
#choice
par(mfrow=c(2,2))
abplot
tegplot
pachyplot
pagurusplot

LabAssayWholeTissue <- read.csv("LabAssaysWholeTissue.csv",header=T)
View(LabAssayWholeTissue)
choice <- LabAssayWholeTissue[1:232,]

fig1<- ggplot(choice, aes(x=algae_spp., y= algae_Wd, fill = algae_spp.)) + geom_boxplot(show.legend = FALSE) + theme_bw()  + xlab("") + ylab("Algae Mass Consumed (g)") + ggtitle("Food Choice Assay") + theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12),plot.title =element_text(hjust = 0.5)) + 
  facet_grid(grazer_spp. ~., scales = "free_y", labeller = as_labeller(c("Haliotis cracherodii" = "H. cracherodii", "Tegula" = "T. funebralis", "Pachy" = "P. crassipes", "Pagurus" = "P. samuelis")),)

fig1

view(choice)

#performance
#this figure only shows final dry mass of non-shell tissue for tegula and red abalone. All other tissue will be in the appendix

fig2<- ggplot(performance, aes(x=diet, y= terminal_dry_mass, fill= diet)) + 
  geom_boxplot(show.legend = FALSE) + theme_bw() + 
  xlab("Diet") + 
  ylab("Dry Tissue Mass (g)") + 
  ggtitle("Herbivore Dry Tissue Mass by Diet") + 
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12), plot.title =element_text(hjust = 0.5)) +
  facet_grid(grazer_spp. ~ ., scales = "free_y", labeller = as_labeller(c("red abalone" = "H. rufescence", "tegula" = "T. funebralis"))) +
  scale_x_discrete(limits = c("starved", "macro", "mixed", "sargassum"), labels=c("starved" = "Starved", "macro" = "M. pyrifera",
                              "mixed" = "Mixed","sargassum" = "S. horneri")) +
   geom_vline(xintercept=c(1.5),linetype="dotted") +
   theme(axis.text.x = element_text(face="italic", 
                           size=10))
fig2
```


#Analysis for manuscript 1

```{r}

#load data
performanceassay<-read.csv("PerformanceAssays2020.csv", header=TRUE,)
view(performanceassay)
na.omit(performanceassay)

#R decided to add phantom rows of NA at the bottom. Subset the dataframe to only keep the rows with actual information
performance <- performanceassay[1:160,]

#performance assay
performance2 <- subset(performance, diet != "starved" ) #filter out the starved treatment for the model
view(performance2)

#check normality
qqnorm(performance2$terminal_dry_mass)
plot(performance2$terminal_dry_mass)

#look at them individually
redabs<-subset(performance2, grazer_spp.== "red abalone")
hist(redabs$terminal_dry_mass)
tegs<-subset(performance2, grazer_spp.== "tegula")
hist(tegs$terminal_dry_mass)


#create simple model 
m <- lm(terminal_dry_mass ~ diet, performance2)
summary(m)
par(mfrow = c(2, 2))
plot(m)
anova(m)

m2<-lm(terminal_dry_mass ~ diet*grazer_spp., performance2)
summary(m2)
par(mfrow = c(2, 2))
plot(m2)
anova(m2)


m3<-glmer(terminal_dry_mass ~ diet*grazer_spp. + (1| est_total_dry_mass_i) , family = gaussian, performance2)
summary(m3)
par(mfrow = c(2, 2))
plot(m3)
anova(m3)

#Tukeys post hoc test
hsd <- HSD.test(m3, trt = 'diet') 
print(m3)
plot(m3)

#check assumptions of ANOVA
# check Levene's test for constant variance
leveneTest(m)
## null hypothesis is that we have constant variance
### P=0.43, do not reject the hypothesis

#check the normality of the residuals
qqnorm(m$residuals)
shapiro.test(m$residuals)
##resuduals are normally distributed

#Tukeys post hoc test
hsd <- HSD.test(m2, trt = 'diet') 
print(hsd)
plot(hsd)

#does differnt diet affect weight of grazers
m3<- glmer(terminal_dry_mass ~ diet*grazer_spp. + (1| est_total_dry_mass_i), data = performance2, family = binomial)

anova(m3)











model2<- aov(terminal_dry_mass ~ diet + est_total_dry_mass_i, data = tegs)
Anova(model2,type="III")

hsd2 <- HSD.test(model2, trt = 'diet') 
print(hsd2)
plot(hsd2)


test<- aov(terminal_dry_mass ~ diet, data = redabs)
Anova(test)

hsd1 <- HSD.test(test, trt = 'diet') 
print(hsd1)
plot(hsd1)





model1<- aov(terminal_dry_mass ~ diet + est_total_dry_mass_i, data = redabs)
Anova(model1,type="III")

hsd <- HSD.test(model1, trt = 'diet') 
print(hsd)
plot(hsd)


test<- aov(terminal_dry_mass ~ diet, data = redabs)
Anova(test)

hsd1 <- HSD.test(test, trt = 'diet') 
print(hsd1)
plot(hsd1)
```
